# see this link for more information
# https://docs.codecov.io/docs/commit-status

codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "30...70"

  status:
    project: off
      # default:
      #  threshold: 2.0
      #  if_not_found: success
    patch: off
    changes: off

ignore:
  # testing the electronic structure code has very low priority
  - "pibronic/vibronic/orthonormal/sequences.py"
  - "pibronic/vibronic/electronic_structure.py"
  - "pibronic/vibronic/model_auto.py"
  - "pibronic/vibronic/model_op.py"
  - "pibronic/vibronic/model_h.py"
  # testing the code which draws code also has low priority
  - "pibronic/plotting/plotting.py"
  - "pibronic/plotting/grid_plots.py"


parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
