# see this link for more information
# https://docs.codecov.io/docs/commit-status

codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "30...70"

  status:
    project: off
      # default:
      #  threshold: 2.0
      #  if_not_found: success
    patch: off
    changes: off

ignore:
  - "pibronic/vibronic/orthonormal/sequences.py"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
