language: python
python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov
  - pip install codecov

cache: pip

before_script:
  - pytest tests/pimc/test_pimc.py

script:
  - pytest --cov=./

after_success:
  - codecov

notifications:
  email: false
